const test = require("node:test");
const assert = require("node:assert/strict");
const { canonicalize, canonicalJsonString, hashRecord } = require("../../shared/canonicalHash");
const vectors = require("../../shared/test-vectors.json");

test("canonicalHash matches the committed test vectors exactly", () => {
  // These vectors were generated by this same module and saved to
  // shared/test-vectors.json. The frontend's copy of this logic (Phase 4)
  // is tested against the identical file, which is what actually proves
  // "same hashing as the frontend" rather than just asserting it in prose.
  for (const vector of vectors) {
    assert.equal(canonicalJsonString(vector.input), vector.canonicalJson, `canonical JSON mismatch for: ${vector.name}`);
    assert.equal(hashRecord(vector.input), vector.hash, `hash mismatch for: ${vector.name}`);
  }
});

test("key order in the input does not affect the canonical JSON or hash", () => {
  const a = { zebra: 1, apple: 2, mango: 3 };
  const b = { mango: 3, apple: 2, zebra: 1 };
  assert.equal(canonicalJsonString(a), canonicalJsonString(b));
  assert.equal(hashRecord(a), hashRecord(b));
});

test("nested key order does not affect the hash", () => {
  const a = { outer: { b: 2, a: 1 } };
  const b = { outer: { a: 1, b: 2 } };
  assert.equal(hashRecord(a), hashRecord(b));
});

test("array element order DOES affect the hash (arrays are not sorted)", () => {
  const a = { list: [1, 2, 3] };
  const b = { list: [3, 2, 1] };
  assert.notEqual(hashRecord(a), hashRecord(b));
});

test("a different value for the same key produces a different hash", () => {
  assert.notEqual(hashRecord({ a: 1 }), hashRecord({ a: 2 }));
});

test("canonicalize rejects undefined values instead of silently dropping them", () => {
  assert.throws(() => canonicalize({ a: undefined }), TypeError);
});

test("hash is a 32-byte 0x-prefixed hex string", () => {
  const h = hashRecord({ a: 1 });
  assert.match(h, /^0x[0-9a-f]{64}$/);
});
